"""Choose the static glyph set, render the font textures and the dynamic
glyph atlas.

Static glyphs live permanently in the game's font pages:
  page 0 cells 87..247 and 264..287 (single byte / F8 xx codes)
  page 1 cells 200..323             (F9 C8..FB / FA 00..47)
Everything the item-name and menu renderers draw must be static. The most
frequent message glyphs fill the remaining static cells; all other glyphs go
into the atlas and are copied into page 1 cells 0..199 by the DLL right
before the message that needs them is shown.

Outputs:
  build/charmap.json      {"static": {char: cell}, "dynamic": [char, ...]}
  build/fonts/PBFONT0.TIM, PBFONT1.TIM, PBFONT3N.TIM
  dll/ko_glyphs.h         atlas bitmaps (14x14, 4bpp, TIM nibble order)
"""
import collections
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import glyphs
import kocodec
import tim

ROOT = os.path.join(os.path.dirname(__file__), '..')
BUILD = os.path.join(ROOT, 'build')

PAGE0_CELLS = list(range(87, 248)) + list(range(264, 288))
PAGE1_STATIC = [288 + c for c in range(kocodec.DYN_CELLS, 324)]
STATIC_CELLS = PAGE0_CELLS + PAGE1_STATIC
# drawn by the ASCII renderer (byte = cell + 36 must fit in a byte)
LOW_CELL_CHARS = '예아니오'


def load_texts():
    """Return (static_texts, message_texts)."""
    static, msgs = [], []
    for path in glob.glob(os.path.join(ROOT, 'translations', '*.json')):
        if os.path.basename(path) == 'documents.json':
            continue  # drawn with a TTF font, not the game font
        for e in json.load(open(path, encoding='utf-8')):
            ko = e.get('ko')
            if not ko:
                continue
            ko = kocodec.normalize(ko)
            if e.get('kind') in ('item', 'menu', 'ascii'):
                static.append(ko)
            else:
                msgs.append(ko)
    return static, msgs


def choose(static_texts, msg_texts):
    need = collections.Counter()
    for t in static_texts:
        need.update(kocodec.glyph_chars(t))
    freq = collections.Counter()
    for t in msg_texts:
        freq.update(kocodec.glyph_chars(t))
    order = list(LOW_CELL_CHARS)
    order += [c for c, _ in need.most_common() if c not in order]
    if len(order) > len(STATIC_CELLS):
        raise SystemExit('static glyphs needed by items/menus exceed capacity: %d' % len(order))
    limit = int(os.environ.get('KOFONT_STATIC_MAX', len(STATIC_CELLS)))  # test hook
    for c, _ in freq.most_common():
        if len(order) >= min(limit, len(STATIC_CELLS)):
            break
        if c not in order:
            order.append(c)
    static = {c: STATIC_CELLS[i] for i, c in enumerate(order)}
    for c in LOW_CELL_CHARS:
        assert static[c] + 36 <= 255
    dynamic = [c for c, _ in freq.most_common() if c not in static]
    return static, dynamic


def cell_xy(cell):
    if cell < 288:
        return 0, (cell % 18) * 14, 28 + (cell // 18) * 14
    c = cell - 288
    return 1, (c % 18) * 14, (c // 18) * 14


def blit(pix, x, y, g):
    for yy in range(14):
        for xx in range(14):
            pix[(y + yy) * 256 + x + xx] = g[yy][xx]


def pack(g):
    """14x14 glyph -> 98 bytes, two pixels per byte, low nibble first."""
    out = bytearray()
    for row in g:
        for x in range(0, 14, 2):
            out.append((row[x] & 15) | ((row[x + 1] & 15) << 4))
    return bytes(out)


def main(game_dir):
    static_texts, msg_texts = load_texts()
    static, dynamic = choose(static_texts, msg_texts)
    os.makedirs(os.path.join(BUILD, 'JPN', 'Data'), exist_ok=True)
    json.dump({'static': static, 'dynamic': dynamic},
              open(os.path.join(BUILD, 'charmap.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=0)

    data = os.path.join(game_dir, 'japanese', 'JPN', 'Data')
    p0 = tim.load(os.path.join(data, 'PBFONT0.TIM'))
    clut_rows = [p0.clut[r * 16:(r + 1) * 16] for r in range(p0.clut_h)]
    pages = [p0.indices(), [0] * (256 * 256)]
    empty = [[0] * 14 for _ in range(14)]
    for cell in PAGE0_CELLS:
        _, x, y = cell_xy(cell)
        blit(pages[0], x, y, empty)
    # cells 23/24 held Japanese 、。; draw ASCII comma and period instead
    for cell, ch in ((23, ','), (24, '.')):
        _, x, y = cell_xy(cell)
        blit(pages[0], x, y, glyphs.cell(ch))
    for ch, cell in static.items():
        pg, x, y = cell_xy(cell)
        blit(pages[pg], x, y, glyphs.cell(ch))

    out = os.path.join(BUILD, 'JPN', 'Data')
    open(os.path.join(out, 'PBFONT0.TIM'), 'wb').write(tim.build_4bpp(256, 256, clut_rows, pages[0]))
    p1 = tim.build_4bpp(256, 256, clut_rows, pages[1])
    open(os.path.join(out, 'PBFONT1.TIM'), 'wb').write(p1)
    open(os.path.join(out, 'PBFONT3N.TIM'), 'wb').write(p1)

    lines = ['/* generated by tools/build_font.py - do not edit */',
             '#include <stdint.h>',
             '#define KO_NUM_GLYPHS %d' % len(dynamic),
             'static const uint8_t ko_glyphs[%d][98] = {' % max(1, len(dynamic))]
    for ch in dynamic:
        lines.append('  {' + ','.join('%d' % b for b in pack(glyphs.cell(ch))) + '}, /* U+%04X */' % ord(ch))
    if not dynamic:
        lines.append('  {0}')
    lines.append('};')
    open(os.path.join(ROOT, 'dll', 'ko_glyphs.h'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('glyphs: %d static (%d needed by items/menus), %d dynamic' % (
        len(static), len(set(c for t in static_texts for c in kocodec.glyph_chars(t))), len(dynamic)))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '4249100_Biohazard'))
