"""Movie subtitles -> dll/ko_movies.h

The Japanese movies PJ (opening), ED4 and ED5 have Japanese subtitles burned
into the picture. The installer links the Korean folder's copies to the
subtitle-free North American movies (english/USA/Movie), and the DLL draws
the Korean subtitles from translations/movie_subtitles.json over them.
Times are frame numbers of the Japanese movie (10 fps).

usage: build_movies.py [game_dir]
"""
import json
import os
import sys

ROOT = os.path.join(os.path.dirname(__file__), '..')

# Japanese movie -> subtitle-free North American movie
US_MOVIES = {'PJ': 'pu.avi', 'ED4': 'eu4.avi', 'ED5': 'eu5.avi'}


def wstr(s):
    out = []
    for c in s.replace('\n', '\r\n'):
        if c.isascii() and c.isprintable() and c not in '"\\':
            out.append(c)
        else:
            out.append('\\x%04x' % ord(c))
    # a hex escape swallows following hex digits: split the literal there
    return 'L"' + '""'.join(_split_hex(out)) + '"'


def _split_hex(parts):
    chunks, cur = [], ''
    for p in parts:
        if cur.endswith(tuple('0123456789abcdef')) and '\\x' in cur[-6:] and p[0] in '0123456789abcdefABCDEF':
            chunks.append(cur)
            cur = ''
        cur += p
    chunks.append(cur)
    return chunks


def main(game_dir):
    subs = json.load(open(os.path.join(ROOT, 'translations', 'movie_subtitles.json'), encoding='utf-8'))
    names = list(US_MOVIES)
    lines = ['/* generated by tools/build_movies.py */',
             'typedef struct { const char *name; uint32_t us_size; } ko_movie;',
             'typedef struct { uint8_t movie; uint16_t start, end; const wchar_t *text; } ko_sub;',
             'static const ko_movie ko_movies[] = {']
    for n in names:
        size = os.path.getsize(os.path.join(game_dir, 'english', 'USA', 'Movie', US_MOVIES[n]))
        lines.append('  {"%s", %d},' % (n, size))
    lines += ['};', 'static const ko_sub ko_subs[] = {']
    for s in subs:
        if s['ko']:
            lines.append('  {%d, %d, %d, %s},' % (names.index(s['movie']), s['start'], s['end'], wstr(s['ko'])))
    lines += ['};', '#define KO_NUM_MOVIES %d' % len(names),
              '#define KO_NUM_SUBS (sizeof ko_subs / sizeof ko_subs[0])']
    open(os.path.join(ROOT, 'dll', 'ko_movies.h'), 'w', encoding='ascii', newline='\n').write('\n'.join(lines) + '\n')
    print('movie subtitles: %d' % len(subs))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '4249100_Biohazard'))
