"""Generate dll/ko_rooms.h: Korean room messages served by the DLL.

The game reads room messages from the RDT file it loaded last; the DLL hooks
that lookup and returns these strings instead, so RDT files stay untouched.
Untranslated messages fall back to the original text.

usage: build_rooms.py [game_dir]
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import cheader
import jptable
import kocodec
import rdt

ROOT = os.path.join(os.path.dirname(__file__), '..')
NONE = 0xFFFFFFFF


def _yesno_tail(b):
    """(start, end) of the bytes between a YESNO code's parameter and the
    following END code, or None."""
    i = 0
    while i < len(b):
        c = b[i]
        if c == 8:
            j = i + 2
            k = j
            while k < len(b) and b[k] != 1:
                k += 2 if b[k] >= 0xF8 else 1
            return j, k
        if c >= 0xF8 or c in (1, 3, 4, 5, 6):
            i += 2
        else:
            i += 1
    return None


def graft_yesno(ko, orig):
    """The bytes after <YESNO:n> are parameters for the choice, not text:
    copy them from the original message."""
    a, b = _yesno_tail(ko), _yesno_tail(orig)
    if not a or not b:
        return ko
    return ko[:a[0]] + orig[b[0]:b[1]] + ko[a[1]:]


def main(game_dir):
    codec = kocodec.Codec()
    tr = {e['jp']: e for e in json.load(open(os.path.join(ROOT, 'translations', 'rdt_messages.json'),
                                             encoding='utf-8'))}
    jp_root = os.path.join(game_dir, 'japanese', 'JPN')
    blob = bytearray()
    blob_index = {}
    dyns = []
    rooms = {}
    nmsg = nmiss = warn = 0
    for stage in sorted(x for x in os.listdir(jp_root) if x.upper().startswith('STAGE')):
        for fn in sorted(os.listdir(os.path.join(jp_root, stage))):
            if not fn.upper().endswith('.RDT'):
                continue
            d = open(os.path.join(jp_root, stage, fn), 'rb').read()
            if not rdt.is_room(d):
                continue
            key = fn.upper()[4:8]  # ROOM1060.RDT -> 1060
            st5 = stage.upper() == 'STAGE5'
            offs = []
            for m in rdt.messages(d):
                jp = jptable.decode(m, stage5=st5)
                e = tr.get(jp)
                if not (e and e.get('ko')):
                    offs.append(NONE)
                    nmiss += 1
                    continue
                if jp not in blob_index:
                    ko = kocodec.layout(kocodec.normalize(e['ko']), jp)
                    for p in kocodec.check(ko):
                        print('warning #%s: %s' % (e['id'], p))
                        warn += 1
                    b, dyn = codec.encode(ko)
                    b = graft_yesno(b, m)
                    blob_index[jp] = len(blob)
                    dyns.append((len(blob), dyn))
                    blob += b
                offs.append(blob_index[jp])
                nmsg += 1
            if any(o != NONE for o in offs):
                rooms[key] = offs
    lines = ['/* generated by tools/build_rooms.py - do not edit */', '#include <stdint.h>']
    lines += cheader.DYN_TYPEDEF
    lines += ['typedef struct { char key[4]; uint32_t count; const uint32_t *offs; } ko_room;',
              '#define KO_NUM_ROOMS %d' % len(rooms)]
    lines += cheader.byte_array('ko_room_blob', blob)
    lines += cheader.dyn_tables('ko_room', dyns)
    for key, offs in sorted(rooms.items()):
        lines.append('static const uint32_t ko_room_%s[%d] = {%s};' % (
            key, len(offs), ','.join('0x%x' % o for o in offs)))
    lines.append('static const ko_room ko_rooms[%d] = {' % max(1, len(rooms)))
    for key, offs in sorted(rooms.items()):
        lines.append('  {"%s", %d, ko_room_%s},' % (key, len(offs), key))
    if not rooms:
        lines.append('  {"", 0, 0}')
    lines.append('};')
    open(os.path.join(ROOT, 'dll', 'ko_rooms.h'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('rooms: %d rooms, %d messages translated, %d untranslated, %d unique, %d bytes, %d warnings' % (
        len(rooms), nmsg, nmiss, len(blob_index), len(blob), warn))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '4249100_Biohazard'))
