"""Generate dll/ko_strings.h from translations/exe_strings.json.

Strings without a Korean translation are left untouched (the game keeps the
Japanese original).
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import cheader
import kocodec

ROOT = os.path.join(os.path.dirname(__file__), '..')


def encode_entry(codec, e):
    """Returns (bytes, dynamic glyph list)."""
    ko = kocodec.normalize(e['ko'])
    kind = e['kind']
    if kind == 'item':
        b, _ = codec.encode(ko, dynamic=False)
        return b + b'\x07', []
    if kind == 'msg':
        ko = kocodec.layout(ko, e['jp'])
        for p in kocodec.check(ko):
            print('warning %s: %s' % (e['id'], p))
        return codec.encode(ko)
    if kind == 'menu':
        b, _ = codec.encode(ko, dynamic=False)
        n = e.get('fixed_len')
        if n:
            if len(b) > n:
                raise SystemExit('%s: %d bytes > fixed %d' % (e['id'], len(b), n))
            b += b'\xfb' * (n - len(b))  # FB is a zero-width no-op in menus
        return b + b'\x01', []
    if kind == 'ascii':
        out = bytearray()
        for ch in ko:
            if ch == ' ':
                out.append(0x20)
            else:
                cell = codec.cells[ch]
                assert cell + 36 <= 255, ch
                out.append(cell + 36)
        return bytes(out) + b'\x00', []
    raise ValueError(kind)


def main():
    codec = kocodec.Codec()
    entries = json.load(open(os.path.join(ROOT, 'translations', 'exe_strings.json'), encoding='utf-8'))
    blob = bytearray()
    refs = []
    dyns = []
    done = 0
    for e in entries:
        if not e.get('ko'):
            continue
        b, dyn = encode_entry(codec, e)
        off = len(blob)
        dyns.append((off, dyn))
        blob += b
        while len(blob) % 4:
            blob.append(0)
        for site, orig in e['sites']:
            refs.append((int(site, 16), int(orig, 16), off))
        done += 1
    lines = ['/* generated by tools/build_exe.py - do not edit */', '#include <stdint.h>']
    lines += cheader.DYN_TYPEDEF
    lines += ['typedef struct { uint32_t site, orig, offset; } ko_ref;',
              '#define KO_NUM_REFS %d' % len(refs)]
    # writable: the game may write into some of its strings
    lines += cheader.byte_array('ko_blob', blob, const=False)
    lines += cheader.dyn_tables('ko_str', dyns)
    lines.append('static const ko_ref ko_refs[%d] = {' % max(1, len(refs)))
    for s, o, off in refs:
        lines.append('  {0x%06x, 0x%06x, %d},' % (s, o, off))
    if not refs:
        lines.append('  {0, 0, 0}')
    lines.append('};')
    open(os.path.join(ROOT, 'dll', 'ko_strings.h'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('exe strings: %d translated, %d refs, %d bytes' % (done, len(refs), len(blob)))


if __name__ == '__main__':
    main()
